### ISSUE TITLE
Contributte(s)

### ISSUE THREAD

**Issue by f3l1x** [contributte/menu-control#41]
- [x] change readme
- [x] create docs
- [x] apply QA 
- [ ] apply phpstan

**Comment by f3l1x** [comment]
Because contributte is all about Nette stuff I would prefer to rename this pkg to contributte/menu-control or menu-component. 

It would be much better name and suits to our plan about some UI components ecosystem.

WDYT @foxycode ?

**Comment by foxycode** [comment]
@f3l1x What about just menu? Datagrid doesn't have control in name too :)

**Comment by f3l1x** [comment]
Well, I hope there will be more components and we're running out of names. For example calendar, contributte/calendar is so common name, don't you think?

**Comment by foxycode** [comment]
@f3l1x Does it make sense to have more components for menu in one org?

**Comment by f3l1x** [comment]
Hi @foxycode. Nope, no more menu components are planned. But take a look at `calendar` component. From the name you don't know if it's GUI control or the business logic handling dates and some calculations.

Thus, I'd prefer to have `-control` postfix. 

But, this is my point of view. If you're not into it I'd understand a we can rename it to contributte/menu. 

Let me know please. We're about to finish this transformation.

**Comment by foxycode** [comment]
@f3l1x Ok, let it be `menu-control` :)

**Comment by f3l1x** [comment]
Well done. Renamed. Let me know, I will publish it to packagist as soon as possible.

**Comment by foxycode** [comment]
@f3l1x You can publish on packagist.

**Comment by f3l1x** [comment]
Done https://packagist.org/packages/contributte/menu-control

**Comment by f3l1x** [comment]
ping @foxycode, could you please work on phpstan?

**Comment by foxycode** [comment]
@f3l1x There are more important things, but yes, I'm planning it. I currently have daughter on vaccation here. Will have more time from half of August.

**Comment by foxycode** [comment]
@f3l1x I tried to add PHPStan and fix errors, but there are lot of things I don't like. Are you really making them less readable in your code just to shut up PHPStan?

Example:
```bash
------ ----------------------------------------------------------------------------------------------- 
  Line   MenuItem.php                                                                                   
 ------ ----------------------------------------------------------------------------------------------- 
  83     Only booleans are allowed in &&, Nette\Application\UI\Presenter|null given on the right side.
  83     Only booleans are allowed in &&, string|null given on the left side.
  89     Only booleans are allowed in an if condition, array<string> given.
 ------ -----------------------------------------------------------------------------------------------
```

Current code:
```php
// $this->getAction() returns ?string
// $this->menu->getActivePresenter() returns ?Presenter
if ($this->getAction() && $this->menu->getActivePresenter()) {
}
```

Fixed for PHPStan:
```php
if ($this->getAction() !== null && $this->menu->getActivePresenter() !== null) {
}
```

I don't like making this longer because error is not possible in this case. What do you think?

**Comment by foxycode** [comment]
@f3l1x Any ideas?

**Comment by f3l1x** [comment]
I will take a look, could you @foxycode open PR? We can set to ignore some rules/complains.

**Comment by foxycode** [comment]
@f3l1x Not sure where I should open PR, problem is in `phpstan-strict-rules` package. I added soem exceptions and fixed the rest of the errors, PHPStan is now added to QA workflow.
