### ISSUE TITLE
Extension 'Contributte\MenuControl\DI\MenuExtension' not found

### ISSUE THREAD

**Issue by mareksloser** [contributte/menu-control#47]
For your info after installation i have this error.

Extension 'Contributte\MenuControl\DI\MenuExtension' not found or is not Nette\DI\CompilerExtension descendant.

installation:

composer require contributte/menu-control

extensions:
  menu: Contributte\MenuControl\DI\MenuExtension

i have to change namespace to

menu: Carrooi\Menu\DI\MenuExtension

And it working now.

**Comment by foxycode** [comment]
What version of Nette are you using? Or better, give me your `composer.json` content.

**Comment by mareksloser** [comment]
{
  "name": "nette/web-project",
  "description": "Nette: Standard Web Project",
  "keywords": ["nette"],
  "type": "project",
  "license": ["MIT", "BSD-3-Clause", "GPL-2.0", "GPL-3.0"],
  "require": {
    "php": ">= 7.3",
    "nette/caching": "~3.0.0",
    "nette/component-model": "~3.0.0",
    "nette/di": "~3.0.0",
    "nette/finder": "~2.5.0",
    "nette/forms": "~3.0.0",
    "nette/http": "~3.0.0",
    "nette/mail": "~3.0.0",
    "nette/robot-loader": "~3.2.0",
    "nette/safe-stream": "~2.4.0",
    "nette/security": "~3.0.0",
    "nette/utils": "~3.0.0",
    "latte/latte": "~2.7.0",
    "tracy/tracy": "~2.7.3",

    "contributte/application": "~0.4.0",
    "contributte/bootstrap": "~0.4.0",
    "contributte/console": "~0.7.1",
    "contributte/translation": "~0.4.1",
    "nextras/orm": "~3.1.0",
    "nextras/secured-links": "~1.5.0",
    "ublaboo/datagrid": "^6.2",
    "nyholm/psr7": "~1.2.1",
    "tustin/psn-php": "~2.1.3",
    "contributte/menu-control": "^2.2"
  },
  "require-dev": {
  },
  "autoload": {
    "classmap": ["app/Bootstrap.php"]
  },
  "minimum-stability": "stable"
}

**Comment by foxycode** [comment]
@mareksloser Namespace was unfortunately changed in release `2.2.1`, which also needs `nette/application` version `3.0.4` which also needs `nette/utils` version `3.1`.

Should be fixed if you update `nette/utils` to `~3.1.0`

https://github.com/contributte/menu-control/releases/tag/2.2.1

**Comment by foxycode** [comment]
I should release new major version after migration to Contributte, but harm is already done, I can't fix it without breaking installations for people who already updated to Contributte namespace.
