### ISSUE TITLE
menu-control/.docs/

### ISSUE THREAD

**Issue by mareksloser** [contributte/menu-control#48]
Hello,

could you fix links?

https://github.com/contributte/menu-control/tree/master/.docs#templates

menu.latte - remove ".docs/" from url
breadcrumbs.latte - remove ".docs/" from url and change correct file to breadcrumbs.latte
sitemap.latte - remove ".docs/" from url

thank you,
Marek

**Comment by foxycode** [comment]
@mareksloser What about sending a PR? :) You can do that from the web editor.

**Comment by mareksloser** [comment]
I have no idea how is it work. I dont know, if i can touch your files or not..

Could you check it, if is it correct? - https://github.com/contributte/menu-control/pull/49

**Comment by foxycode** [comment]
Looks good :) Thank you
