### ISSUE TITLE
Sitemap location URL issue

### ISSUE THREAD

**Issue by panrobert** [contributte/menu-control#50]
Hey there,
I'm new to using menu-control, but when I try generate my sitemap, it always generates location as:
`<loc>http://127.0.0.1http://127.0.0.1/ramico/</loc>`
or
`<loc>http://fuze-technology.comhttp://fuze-technology.com/contact</loc>`.
Every location is like this.

I'm using version 2.2.1
![system_info](https://user-images.githubusercontent.com/46072970/97105380-8d94cf00-16ba-11eb-9959-0ba5e2b5990b.png)

What is it ? Thnak you :-)

**Comment by foxycode** [comment]
I need more info to help you. Paste your `composer.json` and presenter, where you're using sitemap please.

**Comment by foxycode** [comment]
@panrobert Will be fixed in next version. For now, you can use `getRealLink()` instead of `getRealAbsoluteLink()` in your sitemap template.
