### ISSUE TITLE
Option to add another custom template

### ISSUE THREAD

**Issue by mokrys** [contributte/menu-control#62]
Hi, I couldn't find the option to add a custom template.  I get an exception "Call to undefined method [Contributte\MenuControl\UI\MenuComponent::renderFooter". 

Is possible add to config something like:

menu:
        templates:
            menu: %appDir%/Components/Menu/menu.latte
            footer: %appDir%/Components/Menu/footer.latte
            sitemapFront: %appDir%/Components/Menu/sitemapFront.latte
            sitemapXml: %appDir%/Components/Menu/sitemapXml.latte

This config could generate methods like renderMenu(), renderFooter()....

**Comment by foxycode** [comment]
Unfortunately, I don't know how could config generate methods. Also I believe this function would have only little audience.

Menu sopports basic templates: https://github.com/contributte/menu-control/tree/master/.docs#templates

Of course, you can always send PR.
